from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "skills" / "docmate" / "SKILL.md"
SKILL_EN = ROOT / "skills" / "docmate" / "SKILL.en.md"
SKILL_ZH = ROOT / "skills" / "docmate" / "SKILL.zh.md"
DESCRIPTION_PROMPT = ROOT / "docs" / "prompts" / "fill-catalog-descriptions.md"


def test_skill_frontmatter_and_trigger_description_cover_docmate_workflow():
    content = SKILL.read_text()
    lowered = content.lower()

    assert "name: docmate" in content
    assert "documentation qa" in lowered
    assert "stale" in lowered
    assert "implementation-sensitive" in lowered
    assert "documentation gaps" in lowered
    assert "pull request" in content
    assert "merge request" in content


def test_language_skill_templates_are_installable_docmate_skills():
    english = SKILL_EN.read_text()
    chinese = SKILL_ZH.read_text()

    assert "name: docmate" in english
    assert "name: docmate" in chinese
    assert "Required Catalog Step" in english
    assert "必读 Catalog 步骤" in chinese
    assert "references/docmate.catalog.json" in english
    assert "references/docmate.catalog.json" in chinese


def test_skill_requires_catalog_before_repo_selection():
    content = SKILL.read_text()

    assert "references/docmate.catalog.json" in content
    assert "before selecting a repository" in content
    assert "aliases" in content
    assert "path" in content
    assert "docRoots" not in content
    assert "codeRoots" not in content


def test_skill_has_gap_report_and_update_mode_rules():
    content = SKILL.read_text()

    assert "Gap report" in content
    assert "Answer Decision Table" in content
    assert "docs-only ok" in content
    assert "must verify code" in content
    assert "insufficient evidence" in content
    assert "confirmed docs gap" in content
    assert "Evidence Priority" in content
    assert "Classify the request and follow the answer decision table" in content
    assert "Answer directly from documentation with document evidence" in content
    assert "repair may run before the final answer" in content
    assert "a small doc-only fix" in content
    assert "Keep evidence explicit and concise" in content
    assert "source of truth for runtime behavior" in content
    assert "generated docs prove otherwise" in content
    assert "Generated Documentation" not in content
    assert "generated by GitLab CI or scripts" in content
    assert "source file that feeds generation" in content
    assert "Target docs repo" in content
    assert "defaults.update.mode = ask" in content
    assert "defaults.update.mode = auto" in content
    assert "defaults.update.mode = off" in content
    assert "already_fixed_upstream" in content
    assert "do not ask again if the user already confirmed repair" in content
    assert "docmate_update.sh" not in content
    assert "Evidence Chain" not in content
    assert "Evidence chain" not in content
    assert "repair-handoff.template.md" not in content
    assert "Out of scope" not in content


def test_skill_has_no_internal_project_terms():
    content = SKILL.read_text()

    forbidden = [
        "Vi" + "per",
        "VI" + "PER",
        "G1" + "-dev",
        "gitlab.sz." + "sensetime.com",
        ".openclaw/" + "workspace",
    ]
    for term in forbidden:
        assert term not in content


def test_description_fill_prompt_has_safe_write_constraints():
    content = DESCRIPTION_PROMPT.read_text()

    assert "Copy this prompt into your own agent" in content
    assert "docmate.catalog.json.backup-YYYYMMDD-HHMMSS" in content
    assert "Only modify repos[].description" in content
    assert "Do not modify any other field" in content
    assert "Keep the existing repo order" in content
    assert "2-space indentation" in content
    assert "Skip any repo that already has a non-empty description" in content
    assert "Do not guess" in content
    assert "Do not deeply traverse source code, run tests, or use network sources" in content
    assert "80 Chinese characters" in content
    assert "140 characters" in content
    assert "valid JSON" in content
    assert "delete the backup file" in content
